// api/data/route.js
import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    message: `robots.txt generated by www.seoptimer.com
User-agent: *
Disallow: 
Disallow: /cgi-bin/
`,
  });
}
